name: CI - Docker Compose Integration Tests


on:
push:
branches: [ main ]
pull_request:
branches: [ main ]


jobs:
integration-tests:
runs-on: ubuntu-latest


steps:
- name: Checkout repository
uses: actions/checkout@v4


- name: Set up Docker Buildx
uses: docker/setup-buildx-action@v3


- name: Log Docker info
run: |
docker --version
docker compose version || true


- name: Start Docker Compose (build & up)
run: |
docker compose up -d --build


- name: Wait for API to be healthy (poll /health)
run: |
echo "Waiting for API /health to return 200..."
ATTEMPTS=0
MAX=30
until [ $ATTEMPTS -ge $MAX ]
do
STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000/health || echo "000")
echo "Attempt $ATTEMPTS: HTTP $STATUS_CODE"
if [ "$STATUS_CODE" = "200" ]; then
echo "API is healthy."
break
fi
ATTEMPTS=$((ATTEMPTS+1))
sleep 2
done
if [ $ATTEMPTS -ge $MAX ]; then
echo "Timed out waiting for API health endpoint. Showing container logs for debugging..."
docker compose logs --no-color --tail=200
exit 1
fi


- name: Run integration tests inside API container
# -T avoids allocating a TTY; necessary on CI
run: |
docker compose exec -T api python test_app.py


- name: Tear down Compose stack (always run)
if: always()
run: |
docker compose down -v
